### ISSUE TITLE
AdMob crash in cocos2d-x 3.15.1. Android Studio 2.3.3

### ISSUE THREAD

**Issue by edugamesvn** [FirebaseExtended/cocos2dx-cpp-sample#11]
Hi, 
I run AdMob example in cocos2d-x 3.14 it work fine, but I upgrade to cocos 3.15.1 it crash when run on device. I test on Samsung galaxy s6 android 7. This is log:

java.lang.UnsatisfiedLinkError: No implementation found for void org.cocos2dx.lib.Cocos2dxEngineDataManager.nativeSetSupportOptimization(boolean) (tried Java_org_cocos2dx_lib_Cocos2dxEngineDataManager_nativeSetSupportOptimization and Java_org_cocos2dx_lib_Cocos2dxEngineDataManager_nativeSetSupportOptimization__Z)
                                                                                     at org.cocos2dx.lib.Cocos2dxEngineDataManager.nativeSetSupportOptimization(Native Method)
                                                                                     at org.cocos2dx.lib.Cocos2dxEngineDataManager.init(Cocos2dxEngineDataManager.java:149)
                                                                                     at org.cocos2dx.lib.Cocos2dxActivity.onCreate(Cocos2dxActivity.java:288)
                                                                                     at android.app.Activity.performCreate(Activity.java:6942)
                                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
                                                                                     at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by alexames** [comment]
I'll give this a look and see what I find.
